name: Create and upload release on Tag

on:
  push:
    tags:
      - "*"  # Runs for any tag

permissions:
    contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Extract variables
        id: env-context
        run: |
          echo "release-version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "repo-name=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT

      - name: Create tar.gz archive
        run: |
          echo "current dir: $(pwd)"
          echo "current contents: $(ls -lah)"
          echo "repo contents: $(ls -lah repo)"
          tar -C ./repo --exclude='**/.git' -cvzf ${{ steps.env-context.outputs.repo-name }}-${{ steps.env-context.outputs.release-version }}.tar.gz ./${{ steps.env-context.outputs.repo-name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env-context.outputs.repo-name }}-${{ steps.env-context.outputs.release-version }}
          path: ./${{ steps.env-context.outputs.repo-name }}-${{ steps.env-context.outputs.release-version }}.tar.gz
