name: Create and upload release on Tag

on:
  push:
    tags:
      - "*"  # Runs for any tag

permissions:
    contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Extract variables
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Create tar.gz archive
        run: |
          echo "current dir: $(pwd)"
          echo "current contents: $(ls -lah)"
          echo "repo contents: $(ls -lah repo)"
          tar --exclude='**/.git' -cvzf ${{ env.REPO_NAME }}-${{ env.VERSION }}.tar.gz repo/${{ env.REPO_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}-${{ env.VERSION }}
          path: /home/runner/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}-${{ env.VERSION }}.tar.gz
